<a href="https://colab.research.google.com/github/Sabya2/Thyroid-prediction/blob/main/thyroid_ineuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries and data

https://www.kaggle.com/dariomandarino/hypothyroid-multi-dataset/code

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
%matplotlib inline
# import lightgbm as lgb
# from sklearn.model_selection import KFold, cross_val_score
# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import RandomizedSearchCV

In [ ]:
cols = ['age', 'sex', "on thyroxine", "query on thyroxine", "on antithyroid medication", 
        "sick", "pregnant", "thyroid surgery", "i131 treatment", 
         "query hypothyroid", "query hyperthyroid", "lithium", "goitre", 
        "tumor", "hypopituitary", "psych", "TSH measured",
         "TSH", "T3 measured", "T3", "TT4 measured", "TT4", "T4U measured", "T4U", 
        "FTI measured", "FTI", "TBG meausred", 
         "TBG", "referral", "target"]

In [ ]:
# target = increased binding protein, decreased binding protein, negative.

allbp = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allbp.data')
allbp.columns = cols

allbp_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allbp.test')
allbp_test.columns = cols

allbp

     age sex on thyroxine  ... TBG referral          target
0     23   F            f  ...   ?    other  negative.|1442
1     46   M            f  ...   ?    other  negative.|2965
2     70   F            t  ...   ?    other   negative.|806
3     70   F            f  ...   ?      SVI  negative.|2807
4     18   F            t  ...   ?    other  negative.|3434
...   ..  ..          ...  ...  ..      ...             ...
2794  70   M            f  ...   ?      SVI  negative.|3689
2795  73   M            f  ...   ?    other  negative.|3652
2796  75   M            f  ...   ?    other  negative.|1287
2797  60   F            f  ...   ?    other  negative.|3496
2798  81   F            f  ...   ?      SVI   negative.|724

[2799 rows x 30 columns]

In [ ]:
# target = hyperthyroid, T3 toxic, goitre, secondary toxic, negative.

allhyper = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allhyper.data')
allhyper.columns = cols

allhyper_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allhyper.test')
allhyper_test.columns = cols

     age sex on thyroxine  ... TBG referral          target
0     23   F            f  ...   ?    other  negative.|1442
1     46   M            f  ...   ?    other  negative.|2965
2     70   F            t  ...   ?    other   negative.|806
3     70   F            f  ...   ?      SVI  negative.|2807
4     18   F            t  ...   ?    other  negative.|3434
...   ..  ..          ...  ...  ..      ...             ...
2794  70   M            f  ...   ?      SVI  negative.|3689
2795  73   M            f  ...   ?    other  negative.|3652
2796  75   M            f  ...   ?    other  negative.|1287
2797  60   F            f  ...   ?    other  negative.|3496
2798  81   F            f  ...   ?      SVI   negative.|724

[2799 rows x 30 columns]

In [ ]:
# target = hypothyroid, primary hypothyroid, compensated hypothyroid, secondary hypothyroid, negative.

allhypo = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allhypo.data')
allhypo.columns = cols

allhypo_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allhypo.test')
allhypo_test.columns = cols

     age sex on thyroxine  ... TBG referral          target
0     23   F            f  ...   ?    other  negative.|1442
1     46   M            f  ...   ?    other  negative.|2965
2     70   F            t  ...   ?    other   negative.|806
3     70   F            f  ...   ?      SVI  negative.|2807
4     18   F            t  ...   ?    other  negative.|3434
...   ..  ..          ...  ...  ..      ...             ...
2794  70   M            f  ...   ?      SVI  negative.|3689
2795  73   M            f  ...   ?    other  negative.|3652
2796  75   M            f  ...   ?    other  negative.|1287
2797  60   F            f  ...   ?    other  negative.|3496
2798  81   F            f  ...   ?      SVI   negative.|724

[2799 rows x 30 columns]

In [ ]:
# target = replacement therapy, underreplacement, overreplacement, negative.

allrep = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allrep.data')
allrep.columns = cols

allrep_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/allrep.test')
allrep_test.columns = cols

     age sex on thyroxine  ... TBG referral                    target
0     23   F            f  ...   ?    other            negative.|1442
1     46   M            f  ...   ?    other            negative.|2965
2     70   F            t  ...   ?    other  replacement therapy.|806
3     70   F            f  ...   ?      SVI            negative.|2807
4     18   F            t  ...   ?    other            negative.|3434
...   ..  ..          ...  ...  ..      ...                       ...
2794  70   M            f  ...   ?      SVI            negative.|3689
2795  73   M            f  ...   ?    other            negative.|3652
2796  75   M            f  ...   ?    other            negative.|1287
2797  60   F            f  ...   ?    other            negative.|3496
2798  81   F            f  ...   ?      SVI             negative.|724

[2799 rows x 30 columns]

In [ ]:
# target = discordant, negative.

dis = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/dis.data')
dis.columns = cols

dis_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/dis.test')
dis_test.columns = cols

     age sex on thyroxine  ... TBG referral          target
0     23   F            f  ...   ?    other  negative.|1442
1     46   M            f  ...   ?    other  negative.|2965
2     70   F            t  ...   ?    other   negative.|806
3     70   F            f  ...   ?      SVI  negative.|2807
4     18   F            t  ...   ?    other  negative.|3434
...   ..  ..          ...  ...  ..      ...             ...
2794  70   M            f  ...   ?      SVI  negative.|3689
2795  73   M            f  ...   ?    other  negative.|3652
2796  75   M            f  ...   ?    other  negative.|1287
2797  60   F            f  ...   ?    other  negative.|3496
2798  81   F            f  ...   ?      SVI   negative.|724

[2799 rows x 30 columns]

age:				 continuous,?.
sex:				 M,F,?.
on_thyroxine:			 f,t.
query_on_thyroxine:		 f,t.
on_antithyroid_medication:	 f,t.
thyroid_surgery:		 f,t.
query_hypothyroid:		 f,t.
query_hyperthyroid:		 f,t.
pregnant:			 f,t.
sick:				 f,t.
tumor:				 f,t.
lithium:			 f,t.
goitre:				 f,t.
TSH_measured:			 f,t.
TSH:				 continuous,?.
T3_measured:			 f,t.
T3:				 continuous,?.
TT4_measured:			 f,t.
TT4:				 continuous,?.
T4U_measured:			 f,t.
T4U:				 continuous,?.
FTI_measured:			 f,t.
FTI:				 continuous,?.
TBG_measured:			 f,t.
TBG:				 continuous,?.

In [ ]:
new_cols = ["target",'age', 'sex', "on thyroxine", "query on thyroxine", "on antithyroid medication", "thyroid surgery", 
            "query hypothyroid", "query hyperthyroid", "pregnant", "sick",  
            "tumor", "lithium", "goitre", "TSH measured", "TSH", 
            "T3 measured", "T3", "TT4 measured", "TT4", "T4U measured", "T4U", 
            "FTI measured", "FTI", "TBG meausred", "TBG"]

In [ ]:
# target = hypothyroid, negative

hypothyroid = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/hypothyroid.data')
hypothyroid.columns = new_cols
hypothyroid

           target age sex on thyroxine  ... FTI measured  FTI TBG meausred TBG
0     hypothyroid  15   F            t  ...            y   17            n   ?
1     hypothyroid  24   M            f  ...            y    0            n   ?
2     hypothyroid  24   F            f  ...            y    6            n   ?
3     hypothyroid  77   M            f  ...            y   44            n   ?
4     hypothyroid  85   F            f  ...            y   23            n   ?
...           ...  ..  ..          ...  ...          ...  ...          ...  ..
3157     negative  58   F            f  ...            y   95            n   ?
3158     negative  29   F            f  ...            y   98            n   ?
3159     negative  77   M            f  ...            y  104            n   ?
3160     negative  74   F            f  ...            y  137            n   ?
3161     negative  56   F            t  ...            y  143            n   ?

[3162 rows x 26 columns]

In [ ]:
# of no use
ann = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/ann-train.data')
ann_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/ann-test.data')

# of no use
newthyroid = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/new-thyroid.data')
newthyroid

In [ ]:
sick_euthyroid = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/sick-euthyroid.data')
sick_euthyroid.columns = new_cols
sick_euthyroid

              target age sex on thyroxine  ... FTI measured  FTI TBG meausred TBG
0     sick-euthyroid  45   F            f  ...            y  112            n   ?
1     sick-euthyroid  64   F            f  ...            y  123            n   ?
2     sick-euthyroid  56   M            f  ...            y   99            n   ?
3     sick-euthyroid  78   F            t  ...            y   91            n   ?
4     sick-euthyroid  80   M            f  ...            y  120            n   ?
...              ...  ..  ..          ...  ...          ...  ...          ...  ..
3157        negative  40   F            f  ...            y   84            n   ?
3158        negative  69   F            f  ...            y  124            n   ?
3159        negative  58   F            f  ...            y   95            n   ?
3160        negative  29   F            f  ...            y   98            n   ?
3161        negative  56   F            t  ...            y  143            n   ?

[3162 rows x 26 columns]

In [ ]:
# target = sick, negative

sick = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/sick.data')
sick.columns = cols

sick_test = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/sick.test')
sick_test.columns = cols
sick

     age sex on thyroxine  ... TBG referral          target
0     23   F            f  ...   ?    other  negative.|1442
1     46   M            f  ...   ?    other  negative.|2965
2     70   F            t  ...   ?    other   negative.|806
3     70   F            f  ...   ?      SVI  negative.|2807
4     18   F            t  ...   ?    other  negative.|3434
...   ..  ..          ...  ...  ..      ...             ...
2794  70   M            f  ...   ?      SVI  negative.|3689
2795  73   M            f  ...   ?    other      sick.|3652
2796  75   M            f  ...   ?    other  negative.|1287
2797  60   F            f  ...   ?    other  negative.|3496
2798  81   F            f  ...   ?      SVI   negative.|724

[2799 rows x 30 columns]

In [ ]:
# target = 

thyroid = pd.read_csv('/content/drive/MyDrive/Kaggle data/Thyroid raw data/thyroid0387.data')
thyroid.columns = ['age', 'sex', "on thyroxine", "query on thyroxine", "on antithyroid medication", 
        "sick", "pregnant", "thyroid surgery", "i131 treatment", 
         "query hypothyroid", "query hyperthyroid", "lithium", "goitre", 
        "tumor", "hypopituitary", "psych", "TSH measured",
         "TSH", "T3 measured", "T3", "TT4 measured", "TT4", "T4U measured", "T4U", 
        "FTI measured", "FTI", "TBG meausred", 
         "TBG", "target", "referral"]
# thyroid.drop(['referral'], axis = 1, inplace = True)
thyroid

      age sex on thyroxine  ... TBG target      referral
0      29   F            f  ...   ?  other  -[840801014]
1      41   F            f  ...  11  other  -[840801042]
2      36   F            f  ...  26  other  -[840803046]
3      32   F            f  ...  36  other  S[840803047]
4      60   F            f  ...  26  other  -[840803048]
...   ...  ..          ...  ...  ..    ...           ...
9166   56   M            f  ...   ?    SVI  -[870119022]
9167   22   M            f  ...   ?    SVI  -[870119023]
9168   69   M            f  ...   ?    SVI  I[870119025]
9169   47   F            f  ...   ?  other  -[870119027]
9170   31   M            f  ...   ?  other  -[870119035]

[9171 rows x 30 columns]

In [ ]:
thyroid['target'] = thyroid['referral'].str[0]
thyroid

      age sex on thyroxine  ... TBG target      referral
0      29   F            f  ...   ?      -  -[840801014]
1      41   F            f  ...  11      -  -[840801042]
2      36   F            f  ...  26      -  -[840803046]
3      32   F            f  ...  36      S  S[840803047]
4      60   F            f  ...  26      -  -[840803048]
...   ...  ..          ...  ...  ..    ...           ...
9166   56   M            f  ...   ?      -  -[870119022]
9167   22   M            f  ...   ?      -  -[870119023]
9168   69   M            f  ...   ?      I  I[870119025]
9169   47   F            f  ...   ?      -  -[870119027]
9170   31   M            f  ...   ?      -  -[870119035]

[9171 rows x 30 columns]

In [ ]:
print(len(thyroid) + len(allbp) + len(allhyper) + len(allhypo) + 
      len(allrep) + len(dis) + len(hypothyroid)  + 
      len(sick_euthyroid) + len(sick) + len(thyroid))

print( len(allbp) + len(allhyper) + len(allhypo) + 
      len(allrep) + len(dis) + len(hypothyroid)  + 
      len(sick_euthyroid) + len(sick) + len(thyroid))

41460
32289

My next step will be to clean each of the dataset and merge them all to get the final dataset

https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns

https://stackoverflow.com/questions/44252759/pandas-how-to-concatenate-dataframes-with-different-columns

https://stackoverflow.com/questions/21435176/appending-two-dataframes-with-same-columns-different-order

So there are two sets of dataframes. 30 and 26 columns

* need to remove referral from each dataframe
*each dataframe has a different annotation for target, so need to change that on priority
* compare 26 and 30 and look for the missing value or what to drop if need be 
* combine them, order of the columns

for miss matched column arrangement

In [ ]:
import pandas as pd
  
# create a dictionary with five fields each 
data = {
    'A':['A1', 'A2', 'A3', 'A4', 'A5'], 
    'B':['B1', 'B2', 'B3', 'B4', 'B5'], 
    'C':['C1', 'C2', 'C3', 'C4', 'C5'], 
    'D':['D1', 'D2', 'D3', 'D4', 'D5'], 
    'E':['E1', 'E2', 'E3', 'E4', 'E5'] }

df = pd.DataFrame(data)

In [ ]:
import pandas as pd
  
# create a dictionary with five fields each 
data2 = {
    'C':['C10', 'C20', 'C30', 'C40', 'C50'],
    'B':['B10', 'B20', 'B30', 'B40', 'B50'],
    'A':['A10', 'A20', 'A30', 'A40', 'A50'], 
    'D':['D10', 'D20', 'D30', 'D40', 'D50'], 
    'E':['E10', 'E20', 'E30', 'E40', 'E50'] }

df = pd.DataFrame(data2)

# Git colab push

In [1]:
! git

usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.

In [2]:
! git init

Initialized empty Git repository in /content/.git/

In [3]:
!git clone https://github.com/Sabya2/Thyroid-prediction.git

Cloning into 'Thyroid-prediction'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.

In [4]:
 # Check the repository
 ! pwd

/content

In [5]:
# Accessing the file in this repository
%cd Thyroid-prediction/

/content/Thyroid-prediction

In [6]:
# Functions available to use
! git remote -v

origin	https://github.com/Sabya2/Thyroid-prediction.git (fetch)
origin	https://github.com/Sabya2/Thyroid-prediction.git (push)

In [7]:
# status of the repo
! git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [ ]:
# some changes like a new file
! touch firstpython.py
! git status
! git add -A

In [8]:
!git config --global user.email '{sabyasachichakrabarty.96@gmail.com}'
!git config --global user.name '{Sabya2}'

In [9]:
! git config --list

user.email={sabyasachichakrabarty.96@gmail.com}
user.name={Sabya2}
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/Sabya2/Thyroid-prediction.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main

In [10]:
! git commit -a -m "first commit"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean